<?php

namespace Tests\Feature;

use Illuminate\Support\Facades\Log;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;


class ApiProductTest extends TestCase
{

    private $test_subdomain;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->test_subdomain = env('TEST_SUBDOMAIN');
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testGetProduct()
    {
        $this->testStoreProduct();

        $response = $this->get($this->test_subdomain . '/api/v1/product');
        $response->assertStatus(200);

        $response->assertJsonStructure([
            'status',
            'data' => [
                [
                    "id",
                    "name",
                    "slug",
                    "description",
                    "price"
                ]
            ]
        ]);


    }


    public function testStoreProduct()
    {
        $response = $this->post($this->test_subdomain . '/api/v1/product', [
            'name' => 'test',
            'brand_id' => 0
        ]);

        $response->assertStatus(200);
    }
}
